# Generated by Django 2.0.4 on 2018-04-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='item_text',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='project',
            name='item_text',
            field=models.TextField(max_length=3000),
        ),
    ]
