# Generated by Django 2.0.5 on 2018-07-24 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=60, unique=True)),
                ('item_title', models.CharField(max_length=110)),
                ('item_text', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('work_place', models.CharField(max_length=250)),
                ('help_with', models.CharField(max_length=500)),
                ('need_help_with', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=240)),
                ('contact_info', models.CharField(max_length=400)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutInfo',
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='item_text',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='project',
            name='item_text',
            field=models.TextField(max_length=3000),
        ),
    ]
