# Generated by Django 2.0.5 on 2018-07-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0002_auto_20180724_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_info',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='help_with',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='need_help_with',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work_place',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
