# Generated by Django 2.0.5 on 2018-07-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0003_auto_20180725_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
