# Generated by Django 2.0.5 on 2018-07-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0005_auto_20180725_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='подпись'),
        ),
    ]
