# Generated by Django 2.0.5 on 2018-07-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0006_auto_20180726_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
