# Generated by Django 2.0.5 on 2018-07-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0007_auto_20180726_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
